force-app/main/default/objects/Inbound_Order_1sub__e/Inbound_Order_1sub__e.object-meta.xml
<CustomObject>
    <description>Receive orders inbound from external systems.</description>
    <label>Inbound Order 1 Sub</label>
    <pluralLabel>Inbound Orders 1 Sub</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inbound_Order_1sub__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
  >Mostly plan to use this to get the PE infrastructure running and tested before defining further fields. I just didn&apos;t like the sound of a field called &quot;test&quot;.</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_1sub__e/fields/Trace_Id__c.field-meta.xml
<CustomField>
    <fullName>Trace_Id__c</fullName>
    <label>Trace Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order__e/Inbound_Order__e.object-meta.xml
<CustomObject>
    <description>Receive orders inbound from external systems.</description>
    <label>Inbound Order</label>
    <pluralLabel>Inbound Orders</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inbound_Order_Status__c/Inbound_Order_Status__c.object-meta.xml
<CustomObject>
    <description
  >Test/debug/initial processing custom object for wiring up platform event.</description>
    <label>Inbound Order Status</label>
    <nameField>
        <displayFormat>IO{000000}</displayFormat>
        <label>Inbound Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Order Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <externalId>true</externalId>
    <label>Batch Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Event_Uuid__c.field-meta.xml
<CustomField>
    <fullName>Event_Uuid__c</fullName>
    <description>Event UUID for this record</description>
    <label>Event UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description
  >Order Type, which will eventually go into the standard order type field for use as a deterministic partition key.</description>
    <label>Order Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Platform_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Name__c</fullName>
    <externalId>true</externalId>
    <label>Platform Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to store status values during testing</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_Status__c/fields/Trace_Id__c.field-meta.xml
<CustomField>
    <fullName>Trace_Id__c</fullName>
    <label>Trace Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InboundOrderEventSubHandler.cls
public with sharing class InboundOrderEventSubHandler {
  // public static void handleInboundOrders(List<Inbound_Order__e> orderEvents) {
  //   List<Inbound_Order_Status__c> ordersToInsert = new List<Inbound_Order_Status__c>();

  //   System.debug(orderEvents[0].Status__c);

  //   for (Inbound_Order__e orderEvent : orderEvents) {
  //     Inbound_Order_Status__c orderStatus = new Inbound_Order_Status__c();
  //     orderStatus.Status__c = orderEvent.Status__c;
  //     orderStatus.Event_Uuid__c = orderEvent.EventUuid;
  //     orderStatus.Order_Type__c = orderEvent.Type__c;
  //     ordersToInsert.add(orderStatus);
  //   }

  //   insert ordersToInsert;
  // }

  // // todo: make the above method use generic sobject types and get rid of this one
  // public static void handleInboundOrdersSingle(
  //   List<Inbound_Order_1sub__e> orderEvents
  // ) {
  //   List<Inbound_Order_Status__c> ordersToInsert = new List<Inbound_Order_Status__c>();

  //   System.debug(orderEvents[0].Status__c);

  //   for (Inbound_Order_1sub__e orderEvent : orderEvents) {
  //     Inbound_Order_Status__c orderStatus = new Inbound_Order_Status__c();
  //     orderStatus.Status__c = orderEvent.Status__c;
  //     orderStatus.Event_Uuid__c = orderEvent.EventUuid;
  //     orderStatus.Order_Type__c = orderEvent.Type__c;
  //     orderStatus.Trace_Id__c = orderEvent.Trace_Id__c;
  //     ordersToInsert.add(orderStatus);
  //   }

  //   insert ordersToInsert;
  // }

  public static void handleInboundOrders(List<SObject> orderEvents) {
    String batchId = UUID.randomUUID().toString();
    String eventName = orderEvents.getSObjectType().getDescribe().name;
    Datetime timestamp = System.now();

    Tracer.trace(
      (String) orderEvents[0].get('Trace_Id__c'),
      batchId,
      'Trace point start',
      eventName,
      orderEvents.size(),
      timestamp
    );

    List<Inbound_Order_Status__c> ordersToInsert = new List<Inbound_Order_Status__c>();

    System.debug(orderEvents[0].get('Status__c'));

    for (SObject orderEvent : orderEvents) {
      Inbound_Order_Status__c orderStatus = new Inbound_Order_Status__c();
      orderStatus.Status__c = (String) orderEvent.get('Status__c');
      orderStatus.Event_Uuid__c = (String) orderEvent.get('EventUuid');
      orderStatus.Order_Type__c = (String) orderEvent.get('Type__c');
      orderStatus.Trace_Id__c = (String) orderEvent.get('Trace_Id__c');
      orderStatus.Batch_Id__c = batchId;
      orderStatus.Platform_Event_Name__c = eventName;

      ordersToInsert.add(orderStatus);
    }

    insert ordersToInsert;

    timestamp = System.now();

    Tracer.trace(
      (String) orderEvents[0].get('Trace_Id__c'),
      batchId,
      'Trace point stop',
      eventName,
      orderEvents.size(),
      timestamp
    );
  }
}