force-app/main/default/objects/Inbound_Order_1sub__e/Inbound_Order_1sub__e.object-meta.xml
<CustomObject>
    <description>Receive orders inbound from external systems.</description>
    <label>Inbound Order 1 Sub</label>
    <pluralLabel>Inbound Orders 1 Sub</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inbound_Order_1sub__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
  >Mostly plan to use this to get the PE infrastructure running and tested before defining further fields. I just didn&apos;t like the sound of a field called &quot;test&quot;.</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order_1sub__e/fields/Trace_Id__c.field-meta.xml
<CustomField>
    <fullName>Trace_Id__c</fullName>
    <label>Trace Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Order__e/Inbound_Order__e.object-meta.xml
<CustomObject>
    <description>Receive orders inbound from external systems.</description>
    <label>Inbound Order</label>
    <pluralLabel>Inbound Orders</pluralLabel>
</CustomObject>

force-app/main/default/classes/InboundOrderPublisher.cls
public with sharing class InboundOrderPublisher {
  // used to publish events to the subscriber with many partitions
  @future
  public static void publishEvents(
    Integer evtCount,
    String msg,
    String traceId
  ) {
    List<Inbound_Order__e> orderEvents = new List<Inbound_Order__e>();

    for (Integer i = 0; i < evtCount; i++) {
      Inbound_Order__e orderEvent = new Inbound_Order__e(
        Status__c = msg,
        Type__c = 'Saver',
        Trace_Id__c = traceId
      );

      orderEvents.add(orderEvent);
    }

    List<Database.SaveResult> results = EventBus.publish(orderEvents);
    return;
  }

  // duplicate event publisher for the platform event with 1 partition
  @future
  public static void publishEvents1Sub(
    Integer evtCount,
    String msg,
    String traceId
  ) {
    List<Inbound_Order_1sub__e> orderEvents = new List<Inbound_Order_1sub__e>();

    for (Integer i = 0; i < evtCount; i++) {
      Inbound_Order_1sub__e orderEvent = new Inbound_Order_1sub__e(
        Status__c = msg,
        Type__c = 'Saver',
        Trace_Id__c = traceId
      );

      orderEvents.add(orderEvent);
    }

    List<Database.SaveResult> results = EventBus.publish(orderEvents);
    return;
  }

  // for testing initial setup before testing 50k events
  public static void publishEvent(String traceId) {
    // publish a single event in order to validate the event being wired up
    Inbound_Order__e orderEvent = new Inbound_Order__e(
      Status__c = 'Multi Subscriber',
      Type__c = 'Express',
      Trace_Id__c = traceId
    );

    Database.SaveResult resultMulti = EventBus.publish(orderEvent);

    Inbound_Order_1sub__e orderEvent1Sub = new Inbound_Order_1sub__e(
      Status__c = 'Single Subscriber',
      Type__c = 'Express',
      Trace_Id__c = traceId
    );

    Database.SaveResult resultSingle = EventBus.publish(orderEvent1Sub);

    return;
  }
}