force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <description
  >Object to store transaction processing and detail information.</description>
    <label>Request Tracker</label>
    <nameField>
        <label>Trace Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Event_Count__c.field-meta.xml
<CustomField>
    <fullName>Event_Count__c</fullName>
    <label>Event Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Platform_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Event_Name__c</fullName>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>Request Quiddity</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Start_Time_Epoch__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_Epoch__c</fullName>
    <label>Start Time Epoch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Trace_Id__c.field-meta.xml
<CustomField>
    <fullName>Trace_Id__c</fullName>
    <externalId>true</externalId>
    <label>Trace Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TraceHandler.cls
public with sharing class TraceHandler implements Queueable {
  private TraceInfo trace;

  public TraceHandler(TraceInfo trace) {
    this.trace = trace;
  }

  public void execute(QueueableContext context) {
    Datetime timestamp = System.now();

    String quiddityStr = String.valueOf(trace.quiddity);

    Request_Tracker__c trackerRecord = new Request_Tracker__c(
      Name = trace.notes,
      Trace_Id__c = trace.traceId,
      Batch_Id__c = trace.batchId,
      Platform_Event_Name__c = trace.eventName,
      Event_Count__c = trace.eventCount,
      Request_Id__c = trace.requestId,
      Quiddity__c = trace.quiddity,
      Start_Time__c = trace.timestamp,
      Start_Time_Epoch__c = trace.timestamp.getTime()
    );

    Database.SaveResult result = Database.insert(trackerRecord);

    // TODO: handle failures/errors
  }
}